




-- ============================================================
-- Adaptive Deception-Driven Cyber Resilience Validation System
-- Refined SQLite Schema — V2 (Production Ready)
-- ============================================================

-- 1. SESSIONS
-- Created by Member A (SSH Engine), read by Member B
CREATE TABLE IF NOT EXISTS sessions (
    session_id      TEXT PRIMARY KEY,           -- UUID, generated by SSH engine
    sensor_id       TEXT DEFAULT 'local-node-1',-- Future-proofing for multi-instance deployment
    source_ip       TEXT NOT NULL,              -- Standardized naming for security logging
    start_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time        DATETIME,
    duration_secs   INTEGER,                    -- Computed on session close
    total_commands  INTEGER DEFAULT 0,
    status          TEXT DEFAULT 'active' CHECK (status IN ('active', 'closed', 'timeout'))
);

-- 2. COMMANDS
-- Every command captured in the fake shell
CREATE TABLE IF NOT EXISTS commands (
    command_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id      TEXT NOT NULL,
    raw_input       TEXT NOT NULL,
    parsed_command  TEXT,                       -- First token extracted
    timestamp       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    response_type   TEXT CHECK (response_type IN ('rule', 'ai', 'unknown')), 
    response_text   TEXT,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);

-- 3. THREATS
-- Classified threats fed into the chaos engine queue
CREATE TABLE IF NOT EXISTS threats (
    threat_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id      TEXT NOT NULL,
    command_id      INTEGER NOT NULL,           -- Links back to commands table (removes redundant command_text)
    threat_type     TEXT NOT NULL,              -- e.g., CPU_Exhaustion, Malware_Download
    severity        TEXT NOT NULL DEFAULT 'Low' CHECK (severity IN ('Low', 'Medium', 'High')),
    confidence      REAL NOT NULL DEFAULT 1.0,  -- 0.0 to 1.0
    source          TEXT DEFAULT 'rule' CHECK (source IN ('rule', 'ai')),
    timestamp       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed       INTEGER NOT NULL DEFAULT 0 CHECK (processed IN (0, 1)), -- 0 = queued, 1 = done
    FOREIGN KEY (session_id) REFERENCES sessions(session_id),
    FOREIGN KEY (command_id) REFERENCES commands(command_id)
);

-- 4. CHAOS_RESULTS
-- Output of each chaos experiment triggered by a threat
CREATE TABLE IF NOT EXISTS chaos_results (
    experiment_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    threat_id          INTEGER NOT NULL,
    experiment_type    TEXT NOT NULL CHECK (experiment_type IN ('cpu_stress', 'memory_stress', 'disk_io')),
    intensity_level    INTEGER NOT NULL DEFAULT 1, 
    cpu_peak           REAL,                   -- percentage 0-100
    memory_peak        REAL,                   -- percentage 0-100
    disk_io_peak       REAL,                   -- MB/s
    duration_secs      INTEGER,
    recovery_time_secs REAL,
    result             TEXT CHECK (result IN ('Resilient', 'Vulnerable')),
    started_at         DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at       DATETIME,
    notes              TEXT,
    FOREIGN KEY (threat_id) REFERENCES threats(threat_id)
);

DROP TABLE IF EXISTS adaptive_scores; -- Remove the old global version

CREATE TABLE IF NOT EXISTS adaptive_scores (
    session_id            TEXT NOT NULL,
    threat_type           TEXT NOT NULL,
    occurrence_count      INTEGER NOT NULL DEFAULT 0,
    current_severity      TEXT NOT NULL DEFAULT 'Low' CHECK (current_severity IN ('Low', 'Medium', 'High')),
    chaos_intensity_level INTEGER NOT NULL DEFAULT 1,     
    escalation_triggered  INTEGER NOT NULL DEFAULT 0 CHECK (escalation_triggered IN (0, 1)), 
    last_updated          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, threat_type), -- THE CRITICAL FIX
    FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);

-- ============================================================
-- INDEXES for query performance on dashboard + chaos watcher
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_commands_session   ON commands(session_id);
CREATE INDEX IF NOT EXISTS idx_threats_session    ON threats(session_id);
CREATE INDEX IF NOT EXISTS idx_threats_processed  ON threats(processed);
CREATE INDEX IF NOT EXISTS idx_threats_type       ON threats(threat_type);
CREATE INDEX IF NOT EXISTS idx_chaos_threat       ON chaos_results(threat_id);

